initStore([
        {
            id: 0,
            title: 'Horizon: Edge of Ruin (PS5/PS4)',
            description: 'Embark on a journey through a vibrant world ruled by machine beasts.',
            price: 69.95,
            discountPrice: 59.95,
            image: 'img/service-1.jpg',
        },
        {
            id: 1,
            title: 'Warborn: Rise of the North (PS5/PS4)',
            description: 'Step into a mythic realm with a warrior’s destiny and fierce battles.',
            price: 69.95,
            discountPrice: 54.95,
            image: 'img/service-2.jpg',
        },
        {
            id: 2,
            title: 'Torque Drift 5 (Xbox/PC)',
            description: 'Push the limits in a dynamic open-road racer packed with precision cars.',
            price: 59.95,
            discountPrice: 49.95,
            image: 'img/service-3.jpg',
        },
        {
            id: 3,
            title: 'Shadowlands: Fallen Age (PC/PS5/Xbox)',
            description: 'Conquer dark forces in a mystical land filled with danger and secrets.',
            price: 69.95,
            discountPrice: 54.95,
            image: 'img/service-4.jpg',
        },
        {
            id: 4,
            title: 'Haunted Eclipse: Redux (PC/PS5/Xbox)',
            description: 'Revisit a terrifying classic rebuilt with modern visuals and gameplay.',
            price: 59.95,
            discountPrice: 49.95,
            image: 'img/service-5.jpg',
        },
        {
            id: 5,
            title: 'Speed Racers Infinity (Switch)',
            description: 'Join thrilling arcade-style races featuring legendary drivers and tracks.',
            price: 49.95,
            discountPrice: 39.95,
            image: 'img/service-6.jpg',
        },
    ]);